
[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
dependencies = [
    "Keras==2.2.4",
    "numpy==1.18.1",
    "pandas==1.0.1",
    "scikit-learn==0.21.2",
    "stanfordnlp==0.2.0",
    "tensorflow==1.15",
]
requires-python = ">=3.7"
